### ISSUE TITLE
Test with UDP Sockets and shared pointers passes with RUN, fails with DEBUG

### ISSUE THREAD

**Issue by ngjermundshaug** [etas/vs-boost-unit-test-adapter#113]
Hi!

I discovered something strange...

**Code:**
![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/fd47a53e-7c90-4e5e-b1a7-2aee41d98af7/2016-03-31_2249.png)

**Test**
![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/e31bda80-fef8-4cbe-92c3-7536432ac697/2016-03-31_2250.png)

When I RUN the test - it passes in VS2013...
![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/704d9b00-549c-4e01-bc09-9c1b90a77395/2016-03-31_2254.png)

... and also in CMD:
![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/a5a978eb-5089-4326-9182-291f974883c1/2016-03-31_2302.png)

But - when I Debug this test - it fails in **boost/asio/detail/win_mutex.hpp**:
![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/107053e6-c8dc-4212-8de1-b50222eac758/2016-03-31_2255.png)

Callstack:
![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/e34772fc-65f1-48d7-99e0-0027b882d25c/2016-03-31_2258.png)

Is this an error in Boost itself? Or in the Unit Test Adapter?

Running Boost 1.60, have tried with VS test adapter 1.0.6.20 + also latest build - same problem with both.

**Comment by guwirth** [comment]
Hi @ngjermundshaug,

Running with debug did you set a breakpoint?
What happens running debug from command line?

Looking to callstack this happens in Receiver dtor. There is nothing from BUTA on callstack so do not think that this has something to do with adapter. Looks more like an object is no more available during cleanup?

Regards,

**Comment by ngjermundshaug** [comment]
I am able to set a breakpoint in the destructor, it crashes right after that when the destructor method is finished. Will try to run debug from cmd tomorrow morning (8h).

**Comment by ngjermundshaug** [comment]
Hi @guwirth 

Results from running the tests from the command line:
![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/6ac1457c-0ec9-4b65-b687-c62e06b5e3a7/2016-04-01_0915.png)

Also works fine when attaching debugger manually (VS 2013).

Also tried to run the test with the exact same parameters that BUTA uses - works fine.
![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/4fb5af9f-afe8-4926-be90-263e85780e10/2016-04-01_0918.png)

Using BUTA parameters and manually attaching a debugger also works fine:
![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/6b2af146-360d-41e4-b159-26d767b6ed80/2016-04-01_0920.png)



However - when I manually delete listenSocket in the dtor - no errors are thrown when debugging the test.

![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/2948e2e2-8a77-4fb5-92d2-937e3bc3f349/2016-04-01_0931.png)


If listenIoService is deleted before listenSocket - then the exception is thrown again.

So I'm guessing this has to do with smart pointers and the order of object destruction - but why does it only happen when debugging tests through BUTA? 


![](http://i.giphy.com/xTiTnzN4kLuQfUzMju.gif)

**Comment by guwirth** [comment]
Hi,

Race conditions occurs typically randomly. So it's good or bad luck that this happens with BUTA. Looking to the code the listenSocket needs the listenIoService and you have to ensure that listenIoService is the last object which is destroyed. As a rule of thumb you should always mirror the construction/destruction order in ctor/dtor's. You can force this with an explicit reset or by changing the order of the shared pointers in the class. C++ is creating/destroying member variables always in the order they occur in the class. 

Regards,

**Comment by netspiri** [comment]
As @guwirth mentioned, this issue is not related to the adapter per se, and might I add that this is expected behaviour. Order of member destruction is causing the exception - switching lines 22 and 23 in the `Receiver` class declaration should fix the issue. Since you are running the test under a debug scenario, access to destroyed memory is causing the debug runtime environment to trigger the exception. The debug runtime environment is only used when tests are debugged, which explains why this is happening when debugging, and not running the test.

When choosing debug test, the adapter executes the test as though _Debug - Start Debugging_ is selected from Visual Studio's menu bar. We do not use or support the `-w` command line argument at the moment. Additionally, we currently do not support auxiliary arguments via the `--` option. The test module is simply executed within a debug environment as described in https://github.com/etas/vs-boost-unit-test-adapter/blob/master/BoostTestAdapter/Boost/Runner/BoostTestRunnerBase.cs#L124.

For further information, please refer to: https://blogs.msdn.microsoft.com/larryosterman/2008/09/03/anatomy-of-a-heisenbug/.

**Comment by ngjermundshaug** [comment]
Hi @guwirth and @netspiri and thank you for your input on this.

Switching the declaration order did indeed fix the problem. Will pay more notice to declaration order from now on.

Thanks again!
