### ISSUE TITLE
Cancel is not always closing boost executable

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#128]
In case a unit test is in an endless loop 'Cancel' is not working. It seems like the Visual Studio test runner process is ending but not the started BoostXXX.exe process.

How to reproduce:
* write an unit test with an endless loop (e.g. while(1);)
* after starting the unit test press 'Cancel'
* verify with Process Explorer that process is ended

**Comment by netspiri** [comment]
`Cancel` is used to stop further test (batch) execution and this flag is tested in-between test executions. Regarding long-running tests, the test timeout feature was created which can be configured via the `.runsettings` file. By default, the test is allowed to run indefinitely.

This is how the project was designed and is expected behaviour. If this behaviour needs to be changed, please let us know.

**Comment by guwirth** [comment]
Ok understood. For users behaviour seems to be surprising. In case of an endless test they have to end the process (by switching to another tool) always manually before they can continue with development.

**@all how should the tool behave?**

**Comment by guwirth** [comment]
After starting a unit test:
* by default, the test is allowed to run indefinitely
* maximum execution time can be configured via the .runsettings file
* `Cancel` is stopping all tests immediately (terminating also hanging executables)
