### ISSUE TITLE
BOOST_DATA_TEST_CASES are not being discovered

### ISSUE THREAD

**Issue by foobar303** [etas/vs-boost-unit-test-adapter#130]
Pre-release version 1.0.7 does apparently not discover BOOST_DATA_TEST_CASES under all circumstances.
```
------ Run test started ------
Logger initialized. Logging to C:\USERS\[...]\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\E5QQ1JMT.223\BoostTestAdapter.dll.log
Could not locate debug symbols for 'C:\blubb\BoostUnitTest1\x64\Debug\BoostUnitTest1.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
Found test: test2
Executing:   -> [test2]
========== Run test finished: 1 run (0:00:00,760076) ==========
```

![image](https://cloud.githubusercontent.com/assets/2073470/15957280/62b497ba-2eee-11e6-81cf-194a54b4f1cc.png)

I attached a minimal example. Pleases compile and run test on 64 bit (_Test->Test Settings->Default Processor Architecture: X64_)

[BoostTestAdapter.dll.log.zip](https://github.com/etas/vs-boost-unit-test-adapter/files/308569/BoostTestAdapter.dll.log.zip)
[BoostUnitTest1.zip](https://github.com/etas/vs-boost-unit-test-adapter/files/308571/BoostUnitTest1.zip)

**Comment by netspiri** [comment]
Many thanks @foobar303 for the example and attachments.

Debug symbols are not found since you are dynamically linking with Boost Test. In such cases, the debug symbols we try to locate are not available in the compiled test module but in the Boost Test DLL.

This is a known issue and is also mentioned in the [Wiki](https://github.com/etas/vs-boost-unit-test-adapter/wiki/User-Manual#force-list-content-discovery).

Currently, we do not support source code parsing of `BOOST_DATA_TEST_CASE` which is why tests are not being discovered.

@guwirth How should we proceed. Should we add source code support for `BOOST_DATA_TEST_CASE`?

**Comment by guwirth** [comment]
@netspiri I would add the feature because this should be the last version supporting source code parsing.

**Comment by guwirth** [comment]
@foobar303 please test with latest master. You can download it from https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master / release / artefact.

**Comment by foobar303** [comment]
@guwirth, @netspiri: tested version 1.0.7.57 from https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master/job/n6u3sfmpggubg9js/artifacts => it just works! My BOOST_DATA_TEST_CASEs have been successfully recognized w/o specifiying a _.runsettings_ file, source file and line number in the test result pane are correctly referred, too. Great job! Thanks a lot, guys!
