### ISSUE TITLE
Couldn't navigate tests

### ISSUE THREAD

**Issue by sergegers** [etas/vs-boost-unit-test-adapter#133]
It is impossible to navigate tests by double clicking on them in Test Explorer or using F12 key after installing adapter version 1.0.7.57. There is a status bar message appears 'Cannot open the following file xxx.cpp'

**Comment by guwirth** [comment]
@sergegers which Visual Studio version are you using?

**Comment by sergegers** [comment]
VS 2015 U2, boost 1.61

**Comment by netspiri** [comment]
I happened on the same issue by accident just now and I noticed the same message in the status bar. In my case, the path was a relative path.

I managed to fix it by setting the following compilation option:
![fc](https://cloud.githubusercontent.com/assets/6962427/16298892/d6b75aa0-3937-11e6-90eb-3094120c1914.png)

Boost Test makes use of the `__FILE__` macro whose value depends on the `/FC` compilation switch (implicitly defined when using debug options e.g. `/ZI`). Using `/FC` will force the `__FILE__` macro to expand to a fully qualified path, thus allowing the test explorer to correctly navigate to the test case.

**Comment by sergegers** [comment]
@netspiri yep, it works.

**Comment by guwirth** [comment]
@netspiri but seems to be only a workaround. Default setting is `Use Full Paths: No`.
Should work with default settings?

**Comment by netspiri** [comment]
Well, it should but unfortunately we missed this in our initial testing since we focused on debug compilation which implicitly uses the `/FC` switch.

This issue stems from the fact that we switched to `--list_content=DOT` and we now rely on the file paths contained within said representation. If we are to allow users to use the default `/FC` switch value of `No` we need to add additional logic which tries to resolve relative paths. This is not trivial since this will require querying Visual Studio in order to build the rooted/fully-qualified paths from relative ones.

**Comment by guwirth** [comment]
@netspiri maybe you can add your description above to "Troubleshooting" section.

**Comment by netspiri** [comment]
Documentation available on our forked wiki. See [Troubleshooting: Unable To Navigate Test Cases From Test Explorer](user-content-unable-to-navigate-test-cases-from-test-explorer).

**Comment by guwirth** [comment]
@netspiri please merge

**Comment by netspiri** [comment]
Merged as requested
