### ISSUE TITLE
Test execution is significantly slower than the execution through the command line

### ISSUE THREAD

**Issue by sluki** [etas/vs-boost-unit-test-adapter#137]
I have 97 unit tests where each takes less than 1ms to finish (according to the test explorer), however running then all takes around 16s. Running through the command line is basically instant.

It might be due to the extensive logging. In that case I would welcome option to disable logging. Disabling log4net in BoostTestAdapter.dll.config improved time to around 12s which is still not very nice.

**Comment by netspiri** [comment]
Hi @sluki and thank you for your interest in the project.

I think your issue may be related to others which were previously discussed (i.e. #37). In brief, our approach at running test cases is to spawn a process per test case (by default, unless configured otherwise). I tend to believe that this is the performance issue you might be dealing with.

This was a design choice we adopted in effort to have test results made available immediately on a test case level. Configuration should allow you to circumvent this behaviour at the cost of test results being made available once all the test module is executed in its entirety. I would recommend that you try your hand at a different batching mechanisms (via configuration) to see if this improves test execution time.

Regarding logging, I do think we can definitely improve on that front and it might be a good thing to allow configurable logging in the future.

**Comment by sluki** [comment]
Hi @netspiri,
thanks, using the <TestBatchStrategy>Source</TestBatchStrategy> execution time dropped to less than 2s. I could have looked more into wiki before posting issues :)
