### ISSUE TITLE
Test cases looked up by boost macros

### ISSUE THREAD

**Issue by LaoTszy** [etas/vs-boost-unit-test-adapter#145]
The test cases got found based on the boost test macros presence in code, i.e. one need exactly "BOOST_AUTO_TEST_CASE(foo_test)" (or any other test case macro) to be present in the test cpp for the foo_test to be found by the adapter. In case another macro is defined like
`#define MY_TEST(name) BOOST_AUTO_TEST_CASE(SPECIAL_NAMING_MACRO((foo_test))`
and later used as
`MY_TEST(foo_test) {...}`
it is not recognized as a test case.

In case the above mentioned macro SPECIAL_NAMING_MACRO is used directly in the BOOST_AUTO_TEST_CASE the adapter recognizes the macro name as the test name.

**Comment by netspiri** [comment]
Hi @LaoTszy and thank you for your interest in the project.

First impressions seems that this issue is caused by source code discovery.

Could you kindly note if the following: `Discovering (SourceCodeDiscoverer)` is listed in 'Tests' section of the Output Window please? Note that using list content discovery, this issue should be resolved automatically. For more details, please refer to issues #120, #130 and #133. You could also force the use of list content discovery as explained in the [Wiki](https://github.com/etas/vs-boost-unit-test-adapter/wiki/User-Manual#user-content-force-list-content-discovery).

**Comment by LaoTszy** [comment]
Thank you for such a fast reply. And sorry for mistaking my local problems for the adapter issue.

Yes, the `Discovering (SourceCodeDiscoverer)` is there, right after it complains about missing debug symbols, which is probably the root of the problem. Although that is still unclear to me, since the pdb file is right there with the test executable.
