### ISSUE TITLE
Add new 'One-Shot' Test Batch Strategy

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#174]
In Boost.Test provided in Boost 1.63 ([Boost 1.62](http://www.boost.org/doc/libs/1_62_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/run_test.html) as well), the ability to run multiple tests from distinct test suites is possible via the `--run_test` or the `BOOST_TEST_RUN_FILTERS` environment variables.

Create a new test batch strategy which provides users the ability to execute all of the selected tests in one process rather than distinct ones as specified by the 'TestCase' strategy.

Hint(s):
- Before using this test strategy, ensure that the test module is of the appropriate version which supports this feature. Refer to #173 for more information.

**Comment by guwirth** [comment]
@netspiri Both aproches have there advantages:
* Run all together is starting the process only once and is typically faster. In case one test is crashing the process all other tests are not executed. It's typically harder to find the root cause.
* Run one test after the other by starting every time a new process is safer but with worse performance.

Best is if user can select the behaviour.

**Comment by netspiri** [comment]
The intention is to add a new test strategy while leaving the default as is: 'Test Case'. The new strategy will be configurable as already stated in the [Wiki](https://github.com/etas/vs-boost-unit-test-adapter/wiki/User-Manual#configure-test-batching-strategy).
