### ISSUE TITLE
Test cases are not listed in release mode with Visual Studio 2015, Boost 1.59.0

### ISSUE THREAD

**Issue by esj1fe** [etas/vs-boost-unit-test-adapter#205]
I want to run boost unit tests in release mode with Visual Studio 2015. Unfortunately, the test explorer of Visual Studio 2015 does not display any boost unit test in release mode. 

Boost Unit Test Adapter displays the following message:
`Could not locate debug symbols for '...'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.`

However, the release version is built with debug symbols (C7 compatible (/Z7), PDB).

There are no problems in debug mode. All boost unit tests are listed in the test explorer of Visual Studio 2015 and can be executed properly.

Microsoft Visual Studio Enterprise 2015, Version 14.0.25431.01 Update 3
Boost 1.59.0
Boost Unit Test Adapter 1.0.8.44, 1.0.9.25, 1.0.9.222

**Comment by guwirth** [comment]
@esj1fe think has to be clarified what the issue with release build & debug symbols is.

Have you tried <ForceListContent> as proposed in the error message?
https://github.com/etas/vs-boost-unit-test-adapter/wiki/User-Manual#force-list-content-discovery

**Comment by netspiri** [comment]
Hi @esj1fe and thanks for the feedback.

Boost 1.59 is not supported as requested in issue #140.

The fact that discovery is working in debug mode is confusing since, as @guwirth suggested, this might be a product of forcing list_content discovery. Most likely, I think this is happening since the executable 'extension' ends in `.test.boostd.exe` unless a `runsettings` file is in use.

We suggest that you check your configuration properties and make sure that both 'Debug' and 'Release' configurations match. Should this be the case, or an equivalent `runsettings` file is used in both modes of execution, please coordinate with @guwirth should you wish to request the (re-)inclusion of Boost 1.59 support.

**Comment by guwirth** [comment]
@netspiri as far as I understand from https://github.com/etas/vs-boost-unit-test-adapter/issues/197 Boost.Test 1.59 support means searching for one more symbol? If yes I would add it again.

**Comment by netspiri** [comment]
@guwirth It is not as straight-forward as you make it seem.

Due to the introduction of version checking since Boost 1.63 and PR #198 respectively, this complicates things slightly. Since this PR, we now run the executable twice during discovery to acquire the *exact* Boost version. This allows us to react to version differences in a much more convenient manner should things change in Boost.Test in the future.

To recap, we need to make sure to distinguish between the following:

|Version|Debug Symbol|Supports `--version`|Remarks|
|----|----|----|----|
|Boost 1.59|boost::unit_test::runtime_config::list_content|no|Tests are all marked as `disabled` by default in DOT output|
|Boost 1.60|boost::unit_test::runtime_config::LIST_CONTENT|no||
|Boost 1.61|boost::unit_test::runtime_config::LIST_CONTENT|no||
|Boost 1.62|boost::unit_test::runtime_config::LIST_CONTENT|no|Requires `runsettings` workaround|
|Boost 1.63|boost::unit_test::runtime_config::LIST_CONTENT|yes||
|Boost 1.64|boost::unit_test::runtime_config::btrt_list_content|yes||
|Boost 1.65|boost::unit_test::runtime_config::btrt_list_content|yes||

Given that Boost 1.59 notes all tests as disabled by default, this adds yet another challenge which needs to be catered for. It is not just a matter of listing them all as enabled since this might conflict with the actual test conditions, causing a UX issue.

**Comment by guwirth** [comment]
@LukaszMendakiewicz maybe you have an idea?

**Comment by guwirth** [comment]
@netspiri is a namespace also a symbol? Is it possible to search only for `boost::unit_test`?

**Comment by LukaszMendakiewicz** [comment]
That's in the same vein as the discussion in #197. @netspiri mentioned there that they will measure the actual cost of running the symbol scan multiple times.

If that's not prohibitively costly, maybe we can do that, probably in the order of decreasing Boost version not to penalize people moving to the latest.

If it turns out costly, then maybe the solution should be to use the marker file / file name if one wishes to remain on an older Boost version?

Either of the above would still however require the complication for additional workarounds for 1.59, which makes them slightly less attractive... On the other extreme (with apologies to @esj1fe), maybe the adapter should choose to support only that last N releases of Boost (say, 5)?

**Comment by guwirth** [comment]
> Test cases are not listed in release mode with Visual Studio 2015, Boost 1.59:
problems:

1. Boost 1.59 is no more supported from BUTA EXE detection
2. detection in debug mode because of file extension *.test.boostd.exe
3. not detected in release mode because of *.test.boost.exe

* Should not both extension be supported?
* Would also remove the first ´.´ to detect also namings like *.AcceptanceTest.boostd.exe

**Comment by guwirth** [comment]
solved with 1.0.9.34:
https://ci.appveyor.com/api/buildjobs/u3w5u4fwdj1f0n3j/artifacts/BoostTestPlugin%2Fbin%2FRelease%2FBoostUnitTestAdapter.vsix

@esj1fe please try and give us feedback: The default 'ForceListContent' extension has been amended to accept file patterns which match:
* *test.boostd.exe
* *test.boost.exe

There is still no Boost.Test 1.59 support.
