### ISSUE TITLE
Special chars in path not working

### ISSUE THREAD

**Issue by Flamefire** [etas/vs-boost-unit-test-adapter#206]
When the project is in a folder containing special chars (äöüß...) the "GOTO" feature is not working.
VS shows "Cannot open the following file: <path with special chars replaced by "?"-placeholder>

**Comment by netspiri** [comment]
Hi @Flamefire and thanks for the feedback.

Investigated the issue and it seems to be an encoding related issue related to list_content output parsing. Error output stream redirection will output the content using the code page as stated by `chcp` (reference: https://stackoverflow.com/questions/16598785/save-text-file-in-utf-8-encoding-using-cmd-exe)

Currently, we utilise the Stream abstraction which most likely can be fixed by adapting to StreamReader with an explicit encoding.

Will look into this further once time is available. Any help on this issue would also be appreciated.

**Comment by guwirth** [comment]
solved with 1.0.9.33:
https://ci.appveyor.com/api/buildjobs/44xci36q58xih5pf/artifacts/BoostTestPlugin%2Fbin%2FRelease%2FBoostUnitTestAdapter.vsix

@Flamefire please try and give us feedback.
