### ISSUE TITLE
Retrofitting to a legacy exe project

### ISSUE THREAD

**Issue by ksirote** [etas/vs-boost-unit-test-adapter#210]
This is an excellent tool and I would love to use it for the large legacy project I'm working on.

Unfortunately, it is not built as libs, it's a bunch of exes, and it's the code in the exes that I have to test. 

Is it possible to add Boost Unit Test files to the exe project, not as a separate project? 

When I tried, it crashed during the discovery process of the exe...

(I'm using a runsettings file with ForceListContent set to true. I couldn't get it to do anything at all without it)

Any advice?

Microsoft Visual Studio version 14.0.25431
Boost Version: 1_64_0
Adapter Version:  1.0.8.44

**Comment by guwirth** [comment]
Think you should read http://www.boost.org/doc/libs/1_64_0/libs/test/doc/html/boost_test/adv_scenarios.html to understand how to use Boost.Test in your own EXE. Problem is that this extension is calling the EXE with Boost.Test command line parameters. Not sure if this is not in conflict with your EXE usage.

**Comment by netspiri** [comment]
Hi @ksirote and thanks for the support for the project.

Regarding 'ForceListContent':
This is a known issue. We still need to update our adapter to support Boost 1.64 (and now Boost 1.65) to allow proper discovery of such modules without the need of this extra setting.

Regarding 'Discovery Crash':
It would help if you could attempt to run your executable as follows (from the command line):

```bat
test.exe --list_content=DOT 2> list_content.gv
```

If this crashes, then unfortunately we cannot do much from the adapter side. On the other hand, if this succeeds, we need to investigate further since it would most likely be an adapter issue.

Should your executable require different command line arguments to work correctly, you may need to resort to utilising the external test runner settings as noted in the [Wiki](https://github.com/etas/vs-boost-unit-test-adapter/wiki/User-Manual#utilization-of-an-external-test-runner). Example `runsettings`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
    <!-- Test Framework Configuration -->
    <!-- <RunConfiguration /> -->

    <!-- Data Collection Configuration -->
    <!-- <DataCollectionRunSettings /> -->

    <!-- BoostTest Adapter Configuration -->
    <BoostTest>
        <!-- <ForceListContent>true</ForceListContent> -->

        <ExternalTestRunner type=".exe">
            <ExecutionCommandLine>"{source}" --my-custom-argument {boost-args}</ExecutionCommandLine>
        </ExternalTestRunner>
        <Filters>
            <Include>
                <Pattern>test.exe$</Pattern>
            </Include>
        </Filters>
    </BoostTest>        
</RunSettings>
```

**Comment by netspiri** [comment]
Hi @ksirote,

After re-reading your question more in depth, I suspect this might also be related to project setup. As @guwirth hinted, it might be problematic to use the same target executable for both the tests and the actual program, especially since Boost.Test will generate it's own `main` function. There are ways to overcome this as stated in the Boost.Test documentation, but this might require more plumbing both from the programming side and from the adapter side as noted in the previous 'External Test Runner' `runsettings` file.

Your initial suggestion of splitting the project into:
1) Program Executable
2) Core-logic library
3) Test Executable

is a very valid approach to avoid any issues.

If you would like to reduce overhead, another option is to create 2 projects:
1) Program Executable
2) Test Executable

Project (2) would simply re-compile everything in project 1 (except for the file containing `main`) and you should also be able to work around issues with minimal interference. The advantage to this approach is that you have less project maintenance to do but source files will be compiled twice, once per project.

Should you have further feedback on this, please let us know. It would help if we clarify better if this is an adapter issue per so or a project setup issue.

**Comment by ksirote** [comment]
Hi @guwirth  - thanks for your suggestion, I will give it a shot and get back to you. Might take a bit though, other priorities have come up
