### ISSUE TITLE
Support BOOST_DATA_TEST_CASE

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#23]
Support new 1.59 keyword *BOOST_DATA_TEST_CASE*: Declares and registers a data-driven test case, using a particular dataset. See http://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/boost_test/utf_reference/test_org_reference/test_org_boost_test_dataset.html

**Comment by netspiri** [comment]
Given that this is a Boost Test 3 feature (>= Boost 1.59), solving issue #24 should implicitly solve this issue.

I do not think we need to support source code parsing for this macro since Boost Test 2 (<= Boost 1.58) should not have support for this macro to begin with.

**Comment by guwirth** [comment]
I'm not sure. Today it is possible to show the test cases without being able to compile and linke the test binary. If displaying the test cases only after successful build is a use case then you are right.

**Comment by gastart** [comment]
Hello @guwirth.  Visual Studio requires that your boost unit test project builds successfully before it initiates the test discovery.  It would not initiate the test discovery if your project does not build...so technically the only use case that needs to be supported is "displaying the test cases only after successful"

You might have the impression that the tests are somehow being enumerated despite an unsuccessful build is because visual studio does not clear the "tests" that have discovered during *previous successful* builds.

**Comment by guwirth** [comment]
Ok, then #24 should solve this as well.

**Comment by guwirth** [comment]
Shifted to 1.0.7
