### ISSUE TITLE
Add AppVeyor CI

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#30]
Add AppVeyor CI support (http://www.appveyor.com) to repository to verify
1) build on main branch after PR merge
2) build on PR to see if proposed solution is buildable 
3) run tests after binary creation (for 1 & 2)
4) put a status badge on the home page of GitHub project

**Comment by netspiri** [comment]
Tried setting up AppVeyor for building the project but unfortunately we are getting compilation errors due to a slight difference in the build environment.

The issue boils down to a difference in ``Microsoft.VisualStudio.TestPlatform.ObjectModel.dll``. The dll is available on AppVeyor's build environment, it is available in the expected location (``C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow``), and it is available as major version 11 as expected - but there is a difference in the patch version. The version provided with the Visual Studio 2012 SDK and the one which is available on our machines is '11.0.60315.1' whilst the version available on AppVeyor build machines is '11.0.50727.1'.

Attached is the AppVeyor build log which shows that the TestCase.Traits property is not available and this is caused by the dll version difference: [log.txt](https://github.com/etas/vs-boost-unit-test-adapter/files/19268/log.txt).

**Comment by guwirth** [comment]
Could you contact AppVeyor support to clarify this.
Typically they will help.

**Comment by guwirth** [comment]
Seems latest updates of VS2012 are not installed. 11.0.60315.1 belongs to Update 3. In between there is also Update 5 available (http://www.microsoft.com/en-us/download/details.aspx?id=48708). @netspiri please write an update request to AppVeyor.

**Comment by netspiri** [comment]
We are in communication with AppVeyor regarding this issue. Will keep this issue updated should we receive further updates.

**Comment by netspiri** [comment]
New pull-request #38 available which provides AppVeyor CI integration.
