### ISSUE TITLE
High prio for ETAS  "Configurable Test Runner Process Spawning" 

### ISSUE THREAD

**Issue by maschwie** [etas/vs-boost-unit-test-adapter#81]
https://github.com/etas/vs-boost-unit-test-adapter/wiki/User-Manual#group-test-cases
(I found nothing the manual, if this feature somehow should be already possible please hint me the docu and the correct config)

If not, please implement:

When several Test Cases (or a whole test project) are selected in the Visual Studio Test Explorer, the default should be (as done by the NUnit Adapter): 
"Execute all Test Cases in the same spawned Test Runner Process". 

The rest shall be configurable, i.e. for memory leak analysis a mode that spawns a new test runner process per test case makes sense, but this is not a good default behavior from my point of view.

----
Consider the Performance Impact:
Typical .NET and C++ Low Level Unit Test Logik executes << 1 ms (Test Method, or single Test Case). Thus "spawning" a new Test Runner Process per Test Case generates an Overhead easily consuming > 99% of the test-runtime.
Parallelization (i found some discussions here) will not help ... most likely it will even increase the process spawn overhead due to the memory bandwidth contention (dll, symbol loading etc.)

ETAS also does component Tests for MiddleWare and LLVM with Boost
A fast component unit test done e.g. for Scrum Stories executes << 10 ms.
The initial first initialisation of LLVM takes seconds (after process start) 
Even for really fast C++ Middle Ware the initial connection takes approx 200 ms 

Thus "spawning" a new Test Runner Process per Test Case generates overhead worth  99 % of the total test runtime even for more complex test cases.

**Comment by maschwie** [comment]
About Code Coverage Analysis mode (testes with VS 2013): Here the adapter implicitly behaves a bit more clever.
Example: Etas.TargetAccess....Boostd.exe (19 Suites, 50 Test Cases)

Analyze Coverage: 19 Process Spawns (per Suite) of "Etas.TargetAccess....Boostd.exe"  
(instead of 50 in normal mode)
- I found no explict config option in the relevant *,runsettings

Performance
- 50 Spawns would make is unusable
- 19 is still very slow
- 1 would be perfect (NUnit)

Why? New C++ Projects easily generate debug code and symbol output > 1 GB ... if you load that 19x i think on cannot rely on 18 totally cached loads.

**Comment by netspiri** [comment]
Hi @maschwie,

The link you mentioned regarding [test case grouping](https://github.com/etas/vs-boost-unit-test-adapter/wiki/User-Manual#group-test-cases) relates to how to *visually* group the tests. This does not affect the execution of said tests.

Test execution batching has already been implemented. Please refer to issue #37. This fix has not yet been released but should be part of the upcoming 1.0.6.0 release. In the mean time, you can try this feature out by downloading a in-development build from [appveyor](https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master). If you want to enable test execution on a test suite or test executable level, please use the `TestBatchStrategy` configuration element as shown in the [Configuration](https://github.com/etas/vs-boost-unit-test-adapter/wiki/Configuration) page.

Just to recap our design decisions: the main reason why tests execute in an individual process is to have the test adapter responsive. Once a single test completes, we can immediately update the UI with the extracted results. This also provides users the ability to easily interrupt test runs mid-execution. Launching an executable with multiple tests at once will force us to wait until all tests are completed. The BOOST test framework also limits us to execute tests within a single test suite and we cannot execute tests from different test suites. The reason why this behaviour is limited, by default, only to code-coverage is due to users choosing to run code-coverage are generally more interested in the coverage results rather than the test execution outcome. This allows us to 'optimise' in such a manner.

As an additional note, although we appreciate the comparison to the NUnit adapter, please note that the way the NUnit adapter works is by using reflection. The adapter can identify tests and execute them without the need to launch any additional processes. This technique is, unfortunately, not available and not easy to simulate for native BOOST tests.

Sorry for the lengthy response but hope that this clarifies the issue. If you feel that the documentation needs to better represent this information, please feel free to raise your concern.

**Comment by maschwie** [comment]
Thanks - #37 and "TestBatchStrategy" is what we really need, the possibility to configure it should be enough.

The idea about changing the default behavior was too much, when i consider the impact you mentioned on other users that prefer a responsive ui.

And yes, you are right a Reflection Tool definitely can do stuff different when scanning assemblies and invoking the test methods. I did not intend any "unfair comparison" to NUnuit ... the boost runner executable you call much more behaves like a normal customer program. That can be a huge advantage when the the tested code is complex. The NUnit App Domain Features caused us some headache with middle ware thread-pools, the boost runner not :-)
