### ISSUE TITLE
Allow specification of unit-test executable file name(s)

### ISSUE THREAD

**Issue by daniel-kun** [etas/vs-boost-unit-test-adapter#87]
I noticed that the discovery of unit-tests scans every .exe file in the output directory. In our case, this is quite much and hence takes a lot of time: We have 70 .exe files in the output directory, of which only one includes the unit tests.

It would be great if it was possible to specificy which .exe file(s) should be scanned for unit tests.

Seems possible? In line with your other priorities and ideas?

**Comment by netspiri** [comment]
Hi @daniel-kun,

Unfortunately we do not decide which exe to scan since it is Visual Studio which provides us with the exes/dlls upon successful project compilation. We simply register our interest in all .exe/.dll outputs and then try to identify if tests are available in said modules. For further information, please refer to the [Visual Studio Test Platform Primer](https://github.com/etas/vs-boost-unit-test-adapter/wiki/Visual-Studio-Test-Platform-Primer).

We could apply filters to file-names/file-extensions determined via configuration as a post-process step. It is possible, and we will definitely consider it as a future enhancement.

**Comment by daniel-kun** [comment]
Another idea would be to add a "marker" preprocessor directive, such as "BOOST_VS_TEST_THIS" or similar and look for this directive in the project files of the solution and only discover unit tests from those project's output files. What do you think?
Is there technically really no solution to know whether an .exe contains Boost Unit Tests without executing it?

**Comment by netspiri** [comment]
Good idea but we would rather opt for the configuration option using the .runsettings.

The recent `--list_content` function will allow us to disassociate from the Visual Studio IDE. This opens up new possibilities such as allowing the test adapter to run in environments which do not have the IDE, but the necessary tools for testing (e.g. TFS or via `vstest.console`).
