### ISSUE TITLE
Test Batch Strategy 'Source' does not execute properly

### ISSUE THREAD

**Issue by MathiasLohse** [etas/vs-boost-unit-test-adapter#89]
When I set the strategy

    <TestBatchStrategy>Source</TestBatchStrategy>

in the runsettings file, the execution of the selected tests does not execute within one process run.
Instead the execution is done as with strategy

    <TestBatchStrategy>TestSuite</TestBatchStrategy>

Please verify that the strategy >Source< works correctly.

**Comment by maschwie** [comment]
Expected behavior: Select arbitrary e.g. 100 different test cases from 10 suites belonging to 2 test projects (compiled into 2 Boost Test Runner *.exe).  
- mode "source": only 2 process spawns (and 2 global fixture inits)
- mode "suite": 10 process spawns 

p.s.
The major purpose of "Source" from my point should be to: support BOOST_GLOBAL_FIXTURE

**Comment by netspiri** [comment]
HI @MathiasLohse,

Thank you for the report. We will be looking into this.

**Comment by guwirth** [comment]
not reproducible, see #94
