### ISSUE TITLE
support --list_content=DOT

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#93]
From @netspiri

Recently we took some time to look into possible utilities/libraries regarding parsing DOT files. There are many alternatives available, but most of them have a dependency on GraphViz, which we would like to avoid, or have a focus on visualising DOT files.

We came across this project: http://graphviz4net.codeplex.com/. We have not experimented with it yet but it’s .core module contains a DOT parser which might be useful for our cause. Skimming the directory structure seems to show that it was generated using ANTLR (to which the grammar should be available here: http://www.antlr3.org/grammar/1138116546902/dot/). Before prototyping, we would like to know if we are allowed to use parts of this project based on its license. The project uses the LGPL license. The other alternative would be to generate the parser from the grammar directly using ANTLR.

Looking forward to hearing your thoughts regarding this.

**Comment by guwirth** [comment]
My thoughts:
* LGPL license is ok you can use it
* separate DOT parser into own module with own interface (small wrapper) to have possibility to use other component later one
* How big is http://graphviz4net.codeplex.com/? Is it worth to include this component for DOT parser only?
* How easy is it for others to install/use http://graphviz4net.codeplex.com/ if they want to contribute to the project?
* How easy is it to include it into our AppYeyor CI?
* How much work is it to create an own ANTLR parser?

**Comment by daniel-kun** [comment]
Even if graphviz4net is huge, it should be possible to extract the DOT parser into a separate project. You have to talk to the graphviz4net guys, of course. But in this day and age (especially with NuGet) it is "on vogue" to split large libraries into smaller, reusable components, after all.
The project seems to be inactive, though (last commit in 2013). It might even be viable to "fork" the parser in a new, standalone library and ignore graphviz4net altogether.
Speaking of forks, there is one fork with a commit in May 2015: http://graphviz4net.codeplex.com/SourceControl/network/forks/codekaizen/Graphviz4Net
What benefit will supporting --list_content=DOT bring, anyways?

**Comment by guwirth** [comment]
> What benefit will supporting --list_content=DOT bring, anyways?

see #64

**Comment by netspiri** [comment]
@guwirth
- We will consider using LGPL licensed features in the future.
- Yes we can create an adapter interface for better maintainability.
- Our intention was to only import the source files necessary for parsing into our repository and not the whole project.
- Since we would include the sources, it should be as easy as cloning the repository and following the current workflow.
- Whether we we include the source files or the pre-compiled binaries, this should not raise any issues or complications with continuous integration as long as they are part of this repository.
- Given that we have a grammar available, it should be as easy as calling ANTLR to generate a C# parser/lexer. This option should mitigate license issues if we just include the generated parser/lexer and link to the grammar.

@daniel-kun 
As mentioned by @guwirth, label support is one benefit of `--list_content=DOT`. Currently, we 'parse' source files to identify tests which is not always reliable. Using `--list_content=DOT` should provide better test discovery and should be easier to maintain and extend in the future. This will also allow us to reduce the Visual Studio dependency and *may* allow users to use the test adapter in TFS or other environments such as the `vstest.console`.

**Comment by guwirth** [comment]
> Our intention was to only import the source files necessary for parsing into our repository and not the whole project.

Makes sense. Please copy it to an own subfolder, add license information into folder and avoid modifying the copyright of the code.
